name: nexoclom2_dev
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - python=3.12
  - poetry
  - postgresql
  - ipython
  - pip
  - python-dotenv
  - git
  - pylint
  - pip:
    - sphinx
    - stsci_rtd_theme
    - python-semantic-release

variables:
  PGDATA: /Users/mburger/.postgres_dev/main
  NEXOCLOMCONFIG : /Users/mburger/.nexoclom2_dev
